G09projectenII/Models/Session.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace G09projectenII.Models
{
    public class Session
    {

        //Properties
        public decimal Id { get; set; }
        public int Capacity { get; set; }
        public string Description { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public string Externallink { get; set; }
        public string Location { get; set; }
        public string Speakername { get; set; }
        public string Title { get; set; }
        public decimal CalendarId { get; set; }
        public decimal MemberId { get; set; }
        public string Type { get; set; }

        // Nav Properties
        public SessionCalendar Calendar { get; set; }
        public Member Member { get; set; }
        public ICollection<Announcement> Announcements { get; set; }
        public ICollection<SessionAttendees> SessionAttendees { get; set; }
        public ICollection<SessionRegistrees> SessionRegistrees { get; set; }
        public SessionState SessionState { get; set; }

        // Calculated Properties
        public int NumberOfRegistrees => SessionRegistrees.Count();
        public int AvailableRegistrationSpots => (Capacity - SessionRegistrees.Count);
        public Announcement MostRecentAnnouncement => Announcements.OrderBy(a => a.Timestamp).LastOrDefault();
        public int NumberOfAttendees => SessionAttendees.Count;
        public bool HasStarted => SessionState.ToInt() > 1;
        public bool IsOpen => SessionState.ToInt() == 1;

        public Session()
        {
            Announcements = new HashSet<Announcement>();
            SessionAttendees = new HashSet<SessionAttendees>();
            SessionRegistrees = new HashSet<SessionRegistrees>();
        }

        public override string ToString() => string.Join(" | ", Id, Title, Location, Speakername, Type, StartDateTime.ToShortDateString(), StartDateTime.ToShortTimeString()
            , EndDateTime.ToShortDateString(), EndDateTime.ToShortTimeString());


        public void NextState()
        {
            int nextStateIndex = SessionState.ToInt() + 1;
            SessionState = SessionState.FromInt(nextStateIndex <= 3 ? nextStateIndex : 3);
        }

        public void RegisterUser(Member user)
        {
            if (!IsOpen) return;
            if (AvailableRegistrationSpots <= 0) return;
            SessionRegistrees registration = new SessionRegistrees(this, user);
            SessionRegistrees.Add(registration);
            user.SessionRegistrees.Add(registration);
        }

        public void UnregisterUser(Member user)
        {
            SessionRegistrees.Remove(SessionRegistrees.FirstOrDefault(r => r.MemberId == user.MemberId));
            user.SessionRegistrees.Remove(user.SessionRegistrees.FirstOrDefault(r => r.MemberId == user.MemberId));
        }

        public void AttendUser(Member user)
        {
            SessionAttendees attendance = new SessionAttendees(this, user);
            SessionAttendees.Add(attendance);
            user.SessionAttendees.Add(attendance);
        }
    }
}

G09projectenII/Controllers/AdminController.cs
using G09projectenII.Models;
using G09projectenII.Models.Repository_Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace G09projectenII.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class AdminController : Controller
    {
        private readonly ISessionRepository _sessionRepository;
        private readonly IMemberRepository _memberRepository;

        public AdminController(ISessionRepository sessionRepository, IMemberRepository memberRepository)
        {
            _sessionRepository = sessionRepository;
            _memberRepository = memberRepository;
        }

        public IActionResult Index() => RedirectToAction("Sessions");

        public IActionResult Sessions()
        {
            List<Session> nonFinishedSessions =
                _sessionRepository.GetAll()
                    .Where(s => !(s.SessionState is FinishedSessionState))
                    .Where(s => s.Member.Username.Equals(User.Identity.Name) || User.IsInRole("HeadAdmin"))
                    .OrderBy(s => s.StartDateTime)
                    .ToList();

            return View(nonFinishedSessions);
        }

        public IActionResult Attendances()
        {
            List<Session> closedSessions =
                _sessionRepository.GetAll()
                    .Where(s => s.SessionState is ClosedSessionState)
                    .Where(s => s.Member.Username.Equals(User.Identity.Name) || User.IsInRole("HeadAdmin"))
                    .OrderBy(s => s.StartDateTime)
                    .ToList();

            return View(closedSessions);
        }

        [Route("Admin/Session/{id}/Attendances")]
        public IActionResult SessionAttendances(int id)
        {
            var session = _sessionRepository.GetBy(id);
            return session == null ? (IActionResult)NotFound() : View(session);
        }


        [HttpPost]
        public IActionResult ChangeSessionState(int id)
        {
            var session = _sessionRepository.GetBy(id);
            session.NextState();
            _sessionRepository.Update(session);
            _sessionRepository.SaveChanges();

            return RedirectToAction("Sessions");
        }

        [HttpPost]
        public IActionResult AttendUser(int sessionId, int memberId)
        {
            var session = _sessionRepository.GetBy(sessionId);
            var member = _memberRepository.GetBy(memberId);
            session.AttendUser(member);

            _memberRepository.SaveChanges();
            _sessionRepository.SaveChanges();

            return RedirectToAction("SessionAttendances", new { id = sessionId });
        }

    }
}

G09projectenII/Controllers/SessionController.cs
using G09projectenII.Models;
using G09projectenII.Models.Repository_Models;
using G09projectenII.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace G09projectenII.Controllers
{
    public class SessionController : Controller
    {
        private readonly IMemberRepository _memberRepository;
        private readonly ISessionRepository _sessionRepository;

        public SessionController(ISessionRepository sessionRepository, IMemberRepository memberRepository)
        {
            _sessionRepository = sessionRepository;
            _memberRepository = memberRepository;
        }


        [Route("Session/{id}")]
        public IActionResult Index(int id)
        {
            var session = _sessionRepository.GetBy(id);
            var member = _memberRepository.GetBy(HttpContext.User.Identity.Name);

            if (session == null) return NotFound();

            if (member != null)
            {
                ViewBag.MemberIsRegistered = session.SessionRegistrees.Any(r => r.MemberId == member.MemberId);
                ViewBag.MemberHasAttended = session.SessionAttendees.Any(a => a.MemberId == member.MemberId);
            }

            ViewBag.ExtraInfoText = Util.ExtraSessionInfo(session);

            return View(session);
        }

        [HttpPost]
        public ActionResult ToggleRegistration(int sessionId)
        {
            var member = _memberRepository.GetBy(HttpContext.User.Identity.Name);
            var session = _sessionRepository.GetBy(sessionId);

            if (session.SessionRegistrees.Any(r => r.MemberId == member.MemberId))
                session.UnregisterUser(member);
            else
                session.RegisterUser(member);

            _sessionRepository.SaveChanges();
            return RedirectToAction("Index", new { id = sessionId });
        }

    }
}

G09projectenII/ViewComponents/ProfilePicViewComponent.cs
using G09projectenII.Models;
using G09projectenII.Models.Repository_Models;
using G09projectenII.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace G09projectenII.ViewComponents
{
    public class ProfilePicViewComponent : ViewComponent
    {
        private readonly IMemberRepository _memberRepository;

        public ProfilePicViewComponent(IMemberRepository memberRepository) => _memberRepository = memberRepository;

        public IViewComponentResult Invoke(int size = 32, bool rounded = true, Member member = null, string cssClass = "")
        {
            // Use logged in member if no member is given
            if (member == null) member = _memberRepository.GetAll().FirstOrDefault(m => m.Username == User.Identity.Name);

            return View(new ProfilePicViewModel
            {
                Size = size,
                Rounded = rounded,
                CssClass = cssClass,
                // Use placeholder avatar if the member doesn't have a profile picture
                ProfilePicPath = string.IsNullOrEmpty(member?.Profilepicpath) ?
                "/img/avatar.png" : member.Profilepicpath
            });
        }
    }
}

G09projectenII/Views/Admin/Attendances.cshtml
@using System.Diagnostics
@using System.Globalization
@using G09projectenII.Services
@model ICollection<Session>

@{
    ViewBag.Title = "Sessie kiezen";
}
<link href="~/css/attendances.css" rel="stylesheet">

<section>
    <div class="d-flex flex-wrap flex-row justify-content-center justify-content-md-start">

        @if (!Model.Any() || Model == null)
        {
            <p class="text-muted">U heeft geen aanwezigheden te beheren. Sluit hiervoor eerst de inschrijvingen voor een sessie.</p>
        }

        @foreach (var s in Model)
        {
            <div class="card card-width-20 mr-5 mb-5">
                <div class="card-body">
                    <header class="card-title line">
                        <h5><a asp-controller="Session" asp-action="Index" asp-route-id="@s.Id">@s.Title</a></h5>
                        <small class="text-secondary">@s.StartDateTime.ToString("ddd d MMM - HH:mm")</small>
                    </header>
                    
                    <p class="card-text">@s.NumberOfRegistrees ingeschreven <br />@s.NumberOfAttendees aanwezig </p>
                    <a class="btn btn-outline-warning" asp-action="SessionAttendances" asp-route-id="@s.Id">Aanwezigheden beheren</a>
                </div>
            </div>
        }
    </div>
</section>

G09projectenII/Views/Admin/SessionAttendances.cshtml
@using System.Diagnostics
@using System.Globalization
@model Session

@{
    Session s = Model;
    ViewBag.Title = "Aanwezigen beheren";

    var notAttended = s.SessionRegistrees.Where(sr => !sr.IsAlsoAttendee).OrderBy(sr => sr.Member.Username);
    var attended = s.SessionRegistrees.Where(sr => sr.IsAlsoAttendee).OrderBy(sr => sr.Member.Username);
}

<link href="~/css/attendances.css" rel="stylesheet">
<section>
    @if (!s.SessionRegistrees.Any() || s.SessionRegistrees == null)
    {
        <p class="text-muted text-center">Er is niemand ingeschreven voor deze sessie...</p>
    }
    else
    {
        <div class="row">

            <div id="registree-list" class="col-12 col-md-6">
                <h3 class="d-block mb-4">Ingeschrevenen</h3>
                @if (!notAttended.Any())
                {
                    @if (attended.Any())
                    {
                        <p class="text-muted text-center">Alle ingeschrevenen zijn gemarkeerd als aanwezig!</p>
                    }

                }

                @foreach (var sr in notAttended)
                {
                    <div>
                        <div class="card mb-2">
                            <div class="card-body">
                                <header class="card-title float-left">
                                    @await Component.InvokeAsync("ProfilePic", new { width = 20, height = 20, rounded = true, member = sr.Member, cssClass="d-inline align-middle mr-4" })
                                    <div class="d-inline-block align-middle">
                                        <h5>@sr.Member.FullName</h5>
                                        <small class="text-secondary">@sr.Member.Username</small>
                                    </div>
                                </header>

                                <form class="float-right align-middle" asp-controller="Admin" asp-action="AttendUser" asp-route-sessionId="@Model.Id" asp-route-memberId="@sr.MemberId" method="post">
                                    <button type="submit" class="btn btn-outline-success"><i class="fas fa-check"></i></button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            </div>


            <div id="attendee-list" class="mt-5 mt-md-0 col-12 col-md-6">
                <h3 class=" d-block mb-4">Aanwezigen</h3>
                @foreach (var sr in attended)
                {
                    <div>
                        <div class="card mb-2">
                            <div class="card-body">
                                <header class="card-title float-left">
                                    @await Component.InvokeAsync("ProfilePic", new { width = 20, height = 20, rounded = true, member = sr.Member, cssClass = "d-inline align-middle mr-4" })
                                    <div class="d-inline-block align-middle">
                                        <h5>@sr.Member.FullName</h5>
                                        <small class="text-secondary">@sr.Member.Username</small>
                                    </div>
                                </header>
                            </div>
                        </div>
                    </div>
                }


            </div>
        </div>
    }
    </section>

G09projectenII/Views/Admin/Sessions.cshtml
@using System.Diagnostics
@using System.Globalization
@using G09projectenII.Services
@model ICollection<Session>

@{
    ViewBag.Title = "Sessies Beheren";
}

<link href="~/css/manageSessions.css" rel="stylesheet">

<section>
    <div class="panel-group sessions-panel" id="accordion" role="tablist" aria-multiselectable="true">
        
        @if (!Model.Any() || Model == null)
        {
            <p class="text-muted text-center">U heeft geen sessies om te beheren...</p>
        }

        @foreach (var s in Model)
        {
            <div class="panel panel-default">

                <!--Panel Heading-->
                <div class="panel-heading" role="tab" id="@("heading" + s.Id)">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="@("#collapse" + s.Id)" aria-expanded="false" aria-controls="@("collapse" + s.Id)">
                        <!--Date-->
                        <span class="session-date">@s.StartDateTime.ToString("ddd d MMM")</span>
                        <!--Time-->
                            <span class="session-time">@s.StartDateTime.ToString("HH:mm")</span>
                        <!--Title-->
                        <span class="session-title">@s.Title</span>
                        <!--State-->
                        <span class="badge badge-pill session-state @("state" + s.SessionState.ToInt())">@s.SessionState.ToString()</span>
                    </a>

                    <div class="right">

                        @{
                            string sessionStateColor = s.SessionState.ToInt() switch { 0 => "success", 1 => "warning", 2 => "danger", _ => "primary" };
                            string sessionStateVerb = s.SessionState.ToInt() switch { 0 => "Openen", 1 => "Sluiten", 2 => "Afsluiten", _ => "" };

                        }
                        <!--State Change Button-->
                        <button onclick="$('#confirmation-modal-@s.Id').modal()" class="session-state-change btn btn-outline-@sessionStateColor">@sessionStateVerb</button>

                        <!--Chevron-->
                        <a class="collapse-arrow collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="@("#collapse" + s.Id)" aria-expanded="false" aria-controls="@("collapse" + s.Id)">
                            <i class="fas fa-chevron-right"></i>
                        </a>
                    </div>
                </div>


                <!--Panel Body-->
                <div id="@("collapse" + s.Id)" class="panel-collapse collapse" role="tabpanel" aria-labelledby="@("heading" + s.Id)">
                    <div class="panel-body">
                        @if (!string.IsNullOrEmpty(s.Description))
                        {
                            <!--Description-->
                            <div class="session-description"><b>Beschrijving:</b><p>@Html.Raw(s.Description)</p></div>
                        }

                        <!--See more-->
                        <a class="see-more-link" asp-controller="Session" asp-action="Index" asp-route-id="@s.Id">Zie meer...</a>

                    <div class="session-practical-info">
                        @if (!string.IsNullOrEmpty(s.Location))
                        {
                            <!--Location-->
                            <span><i class="fas fa-map-marker-alt"></i>@Html.Raw(s.Location)</span>
                        }
                        <!--Organizer-->
                        <span><i class="fas fa-user"></i>@Html.Raw(s.Member.Firstname) @Html.Raw(s.Member.Lastname)</span>
                        
                        <!--Extra info-->
                        <span> <i class="fas fa-pencil-alt"></i> @(Util.ExtraSessionInfo(s)) </span>
                    </div>
                    </div>
                </div>
            </div>

            <!--Confirmation modal-->
            <div id="confirmation-modal-@s.Id" class="modal" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Waarschuwing</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Bent u zeker dat u de sessie <em>"@s.Title.Trim()"</em> wilt @sessionStateVerb.ToLower()?</p>
                        </div>
                        <div class="modal-footer">
                            <form asp-action="ChangeSessionState" asp-route-id="@s.Id" method="post">
                                <!--State Change Button-->
                                <button type="submit" class="btn btn-outline-@sessionStateColor">@sessionStateVerb</button>
                            </form>
                            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
</section>