G09projectenII/Controllers/CalendarController.cs
using G09projectenII.Models;
using G09projectenII.Models.DTOs;
using G09projectenII.Models.Repository_Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Controller = Microsoft.AspNetCore.Mvc.Controller;

namespace G09projectenII.Controllers
{
    public class CalendarController : Controller
    {
        private readonly ISessionRepository _sessionRepository;
        private readonly IMemberRepository _memberRepository;

        public CalendarController(ISessionRepository sessionRepository, IMemberRepository memberRepository)
        {
            _sessionRepository = sessionRepository;
            _memberRepository = memberRepository;
        }

        public IActionResult Index() => View(_sessionRepository.GetAll());

        [HttpGet]
        public JsonResult GetSessionBy(int id)
        {
            var session = _sessionRepository.GetBy(id);
            return session != null ? Json(new SessionDTO(session)) : null;
        }

        [HttpGet]
        public JsonResult GetRegistrationStatus(int sessionId)
        {
            var member = _memberRepository.GetBy(HttpContext.User.Identity.Name);
            var session = _sessionRepository.GetBy(sessionId);

            if (member == null) return Json("");

            bool hasAttended = session.SessionAttendees.Any(sa => sa.MemberId == member.MemberId);
            bool isRegistered = session.SessionRegistrees.Any(sr => sr.MemberId == member.MemberId);

            return Json(new RegistrationStatusDTO() { HasAttended = hasAttended, IsRegistered = isRegistered });
        }
    }
}

G09projectenII/ViewComponents/ProfilePicViewComponent.cs
using G09projectenII.Models;
using G09projectenII.Models.Repository_Models;
using G09projectenII.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace G09projectenII.ViewComponents
{
    public class ProfilePicViewComponent : ViewComponent
    {
        private readonly IMemberRepository _memberRepository;

        public ProfilePicViewComponent(IMemberRepository memberRepository) => _memberRepository = memberRepository;

        public IViewComponentResult Invoke(int size = 32, bool rounded = true, Member member = null, string cssClass = "")
        {
            // Use logged in member if no member is given
            if (member == null) member = _memberRepository.GetAll().FirstOrDefault(m => m.Username == User.Identity.Name);

            return View(new ProfilePicViewModel
            {
                Size = size,
                Rounded = rounded,
                CssClass = cssClass,
                // Use placeholder avatar if the member doesn't have a profile picture
                ProfilePicPath = string.IsNullOrEmpty(member?.Profilepicpath) ?
                "/img/avatar.png" : member.Profilepicpath
            });
        }
    }
}

G09projectenII/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/favicon-16x16.png">
<link rel="manifest" href="~/manifest.json">
<link rel="mask-icon" href="~/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

G09projectenII/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="nl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title | Lorem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;600;700;800&family=Comfortaa:wght@700&display=swap" rel="stylesheet">

    <!-- calendar stuff -->
    <link href="~/lib/fullcalendar/core/main.css" rel="stylesheet" />
    <link href="~/lib/fullcalendar/daygrid/main.css" rel="stylesheet" />
    <partial name="_Favicons.cshtml" />


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!--Logo-->
                <a class="navbar-brand brand" asp-area="" asp-controller="Calendar" asp-action="Index"><img src="~/img/Logo.svg" class="nav-logo"/><span class="brand-text">Lorem</span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <!-- Navbar items for admins-->
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && (User.IsInRole("HeadAdmin") || User.IsInRole("Admin")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Kalender</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Sessions">Sessies Beheren</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Attendances">Aanwezigheden</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        <!--FB Link-->
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-outline-dark nav-facebook-button" target="_blank" href="https://www.facebook.com/IT-Lab-Hogeschool-Gent-2040310702935554/"><i class="fab fa-facebook-f"></i>
                                <p class="ml-1 d-inline d-sm-none d-md-inline">IT Lab HoGent</p></a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <!--Profile image with dropdown-->
                            <li class="nav-item dropdown d-none d-sm-inline">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @await Component.InvokeAsync("ProfilePic")
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <h6 class="dropdown-header">
                                        @User.Identity.Name
                                        @{
                                            if (User.IsInRole("HeadAdmin"))
                                            {<span class="badge badge-pill badge-primary badge-membertype">Hoofdadmin</span>}
                                            if (User.IsInRole("Admin"))
                                            {<span class="badge badge-pill badge-primary badge-membertype">Admin</span>}
                                        }
                                    </h6>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout">
                                        <svg class="bi bi-box-arrow-left" width="1em" height="1em" viewBox="0 0 16 16" fill="black" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M4.354 11.354a.5.5 0 000-.708L1.707 8l2.647-2.646a.5.5 0 10-.708-.708l-3 3a.5.5 0 000 .708l3 3a.5.5 0 00.708 0z" clip-rule="evenodd"/>
                                            <path fill-rule="evenodd" d="M11.5 8a.5.5 0 00-.5-.5H2a.5.5 0 000 1h9a.5.5 0 00.5-.5z" clip-rule="evenodd"/>
                                            <path fill-rule="evenodd" d="M14 13.5a1.5 1.5 0 001.5-1.5V4A1.5 1.5 0 0014 2.5H7A1.5 1.5 0 005.5 4v1.5a.5.5 0 001 0V4a.5.5 0 01.5-.5h7a.5.5 0 01.5.5v8a.5.5 0 01-.5.5H7a.5.5 0 01-.5-.5v-1.5a.5.5 0 00-1 0V12A1.5 1.5 0 007 13.5h7z" clip-rule="evenodd"/>
                                        </svg>
                                        Uitloggen
                                    </a>
                                </div>
                            </li>

                            <!--Logout text for hamburger menu-->
                            <li class="nav-item flex-grow-1 d-sm-none">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Uitloggen</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item flex-grow-1">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">Inloggen</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        <div class="container">
            <partial name="_CookieConsentPartial" />
        </div>
        <div class="container">

            @RenderBody()

        </div>
    </main>

    <footer class="border-top footer">
        <p class="text-center">Made with <span>♥</span> by the Code Commanders</p>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>